### ISSUE TITLE
OmniMarkupPreviewer's pygments conflicts with Evenote's one

### ISSUE THREAD

**Issue by Explorare** [bordaigorl/sublime-evernote#106]
Evernote package will cause OmniMarkupPreviewer crashed when open doc with code blocks like this

    [PowerAdapter] -(Power)--> [Arndale] --(RS232)--> [LinuxHost]
                                    |                    |
                                 (ether)               (ether)
                                    |                    |
                               [Ether switch] <---------+

And here is error log

    OmniMarkupPreviewer: [ERROR] Exception occured while rendering using MarkdownRenderer
      Traceback (most recent call last):
        File "/root/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/RendererManager.py", line 266, in render_text
        rendered_text = renderer.render(text, filename=filename)
        File "/root/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/MarkdownRenderer.py", line 36, in render
        extensions=self.extensions)
        File "/root/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/libs/markdown/__init__.py", line 411, in markdown
        return md.convert(text)
        File "/root/.config/sublime-text-3/Packages/OmniMarkupPreviewer/OmniMarkupLib/Renderers/libs/markdown/__init__.py", line 288, in convert
        self.lines = prep.run(self.lines)
        File "/root/.config/sublime-text-3/Packages/OmniMarkupPreviewer/    OmniMarkupLib/Renderers/libs/markdown/extensions/fenced_code.py", line 140, in run
        code = highliter.hilite()
        File "/root/.config/sublime-text-3/Packages/OmniMarkupPreviewer/    OmniMarkupLib/Renderers/libs/markdown/extensions/codehilite.py", line 90, in hilite
        lexer = get_lexer_by_name(self.lang)
        File "/root/.config/sublime-text-3/Installed Packages/Evernote.sublime-package/lib/pygments/lexers/__init__.py", line 87, in get_lexer_by_name
        if _alias.lower() in aliases:
      AttributeError: 'NoneType' object has no attribute 'lower'

This problem is also submitted [here] (https://github.com/timonwong/OmniMarkupPreviewer/issues/69) in issue for OmniMarkupPreviewer.

Please help, thanks.

**Comment by bordaigorl** [comment]
@Explorare thanks a lot for bringing my attention to this.
I am planning to update pygments to v2.0.2 (see #102) I wonder if that would help.
I'll see if I can avoid fiddinling with `sys.path` to load `pygments` so the two packages can coexist.

**Comment by bordaigorl** [comment]
I just pushed some changes in `devel` among which b68963acfe8d9d550de3895cb6e1284d314c3c8a
that updates `pygments`.
Could you maybe test if this solves the issue? Thanks!

**Comment by Explorare** [comment]
Problem fixed. It works well again. Thanks for your help.
