### ISSUE TITLE
Version 2.7.1 ailing with an ImportError

### ISSUE THREAD

**Issue by mwcraig** [bordaigorl/sublime-evernote#141]
After updating today to this version, running this plugin fails, with this output in the console:

```
reloading settings Packages/User/Evernote.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "sublime_evernote in /Users/mcraig/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package", line 540, in run
  File "sublime_evernote in /Users/mcraig/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package", line 320, in load_settings
ImportError: No module named 'pygmstyles'
```

**Comment by bordaigorl** [comment]
Hi, thanks for the report.
This may have to do with the new dependency on pygments.
Can you check that:
1. you have an updated version of Package Control
2. you restarted ST (maybe even twice) after updating

Thanks

**Comment by mwcraig** [comment]
A quit and restart fixed the problem, thanks!
