### ISSUE TITLE
Pygments error in Sublime console

### ISSUE THREAD

**Issue by skotzko** [bordaigorl/sublime-evernote#178]
Every time I fire up Sublime, I get this error in the console:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "sublime_evernote in /Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package", line 1491, in plugin_loaded
  File "sublime_evernote in /Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package", line 320, in load_settings
  File "/Users/andrew/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package/lib/pygmstyles/github.py", line 16, in <module>
ImportError: No module named 'pygments.style'
```

Is a file missing?

**Comment by bordaigorl** [comment]
`pygments` is a dependency of the plugin.
If you installed it through Package Control you may need a couple of ST reboots so that PC can install the dependencies.
If you installed the plugin manually you also need to install the `pygments` plugin (see https://github.com/packagecontrol/pygments)

**Comment by doug-w** [comment]
Bumping this, tried installing today after updating to Sublime Text 3 (Build 3143)

`Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/Evernote/Evernote.sublime-settings
reloading plugin Evernote.sublime_evernote
generating syntax summary
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "sublime_evernote in /Users/doug/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package", line 561, in run
  File "sublime_evernote in /Users/doug/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package", line 320, in load_settings
  File "/Users/doug/Library/Application Support/Sublime Text 3/Installed Packages/Evernote.sublime-package/lib/pygmstyles/github.py", line 16, in <module>
ImportError: No module named 'pygments.style'`

**Comment by doug-w** [comment]
Pygments is definitely installed in Packages but it's not able to be imported there for whatever reason with the new Sublime Text 3.  I worked around it by setting a user setting of:
"code_highlighting_style": null

**Comment by SleepyBrett** [comment]
Every time I start up I get this:

```
Package Control: Installing 1 missing dependency
Package Control: Installed missing dependency pygments
Package Control: No updated packages
```

pygments is installed...
