### ISSUE TITLE
Evernote error: [Enml validation]

### ISSUE THREAD

**Issue by gstalnaker** [bordaigorl/sublime-evernote#76]
Cannot post file to Evernote. No idea why it's throwing this error. Other markdown docs work fine. I can't see what's different about this one. Full debug traceback below. Simple form of error from ST3 console:

```
Evernote error: [Enml validation]
	Attribute name "FORM" associated with an element type "DOCUMENT" must be followed by the ' = ' character.
	Last command:  {}
```

Regards,

Guy S.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1825, in is_enabled
    return super(SublimecodeintelDisableLiveCommand, self).is_enabled(True, False)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1835, in is_enabled
    return super(SublimecodeintelDisableLiveLangCommand, self).is_enabled(True, True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1793, in is_enabled
    return super(SublimecodeintelDisableCommand, self).is_enabled(True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1820, in is_enabled
    return super(SublimecodeintelEnableLiveCommand, self).is_enabled(False, False)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1830, in is_enabled
    return super(SublimecodeintelEnableLiveLangCommand, self).is_enabled(False, True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1803, in is_enabled
    enabled = super(SublimecodeintelLiveCommand, self).is_enabled(True)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 438, in is_enabled_
    ret = self.is_enabled(**args)
TypeError: is_enabled() got an unexpected keyword argument 'action'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 442, in is_enabled_
    ret = self.is_enabled()
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1788, in is_enabled
    return super(SublimecodeintelEnableCommand, self).is_enabled(False)
  File "C:\Users\jstalnak\AppData\Roaming\Sublime Text 3\Packages\SublimeCodeIntel\SublimeCodeIntel.py", line 1773, in is_enabled
    enabled = enabled and codeintel_enabled(view, True) == active
TypeError: codeintel_enabled() takes from 0 to 1 positional arguments but 2 were given
Evernote: <h3>Perceptive eForm Process</h3>

<h4>Basic System Topology</h4>

<h5>Test</h5>

<p>Servers are:</p>

<ol>
<li>ImageNow
A.  Hostname: polynomial.doit.wisc.edu
A.  Paths
    i.  Data definitions, Presentations, Shared files: e:\inserver6\worksheets
    i.  imagenowforms.xml: e:\inserver6\etc</li>
<li>Forms Server
A.  Hostname: curve.doit.wisc.edu
A.  Use Windows Services to bounch Tomcat (?)</li>
</ol>

<h5>Prod</h5>

<p>Servers are:</p>

<ol>
<li>ImageNow
A.  Hostname: parabola.doit.wisc.edu
A.  Paths
    i.  Data definitions, Presentations, Shared files: e:\inserver6\worksheets
    i.  imagenowforms.xml: e:\inserver6\etc</li>
<li>Forms Server
A.  Hostname: conic.doit.wisc.edu
A.  Use Windows Services to bounch Tomcat (?)</li>
</ol>

<h5>What's Where</h5>

<p>Two types of <strong>form</strong> objects in ImageNow:</p>

<ol>
<li><strong>Worksheets</strong> are created with the Form Designer, associated with a DocTypes, and published. They are used from within the ImageNow client and are visible when a doctype with which they are associated is open. Use the <strong>Document Viewer</strong> option <strong>View Forms</strong> (F12) to show the <strong>Form Viewer</strong> pane on which is a dropdown menu of avaiable worksheets. See <strong>Forms</strong> next for a complicating issue. These worksheets allow post-import data manipulation via the worksheet's form fields (rather than, say, using the IndexKey/Custom Property view to manually edit field contents).</li>
<li><strong>eForms</strong> can also be created with the Form Designer and associated with a DocType, and published, and manipulated with the ImageNow client. But, they can also be presented to end-users via the Form Server. There need be no difference in functionality between an eForm and  a worksheet. But one major difference is that using a worksheet requires the IN client and an IN account. Using an eForm does not require an IN account and thus any UW entity can be the target audience for an eForm including registered students. The major caveat is that the Form Server uses a java applet to deliver the content to the end-user, so the browser/OS must have java technologies installed and correctly configured in the browser being used.</li>
<li>Because of the differences between these two types of forms, there is a file that contains specifications for which of the forms are in fact <strong>eForms</strong>, the .xml file located in c:\inserverg\etc\imagenowforms.xml. In this file will be a separate <DOCUMENT FORM> entry for each published <strong>eForm</strong>.  It will only contain <strong>eForms</strong> which are delivered by the Form Server and does not list <strong>Worksheets</strong>. At present there is <em>no</em> internal documentation that lists/shows which of the forms in e:\inserver6\worksheets\data_definition are <strong>eForms</strong> or <strong>Worksheets</strong> -- if a record is kept, it must be done manually.</li>
<li>Configuration of <strong>Worksheets</strong> and <strong>eForms</strong>
A.  All <strong>Worksheets</strong> and <strong>eForms</strong> will have their Data Definiton xml, Presentation xsl, and other files on the primary ImageNow server:
    i.  Data Definition files: c:\inserver6\worksheet\data_definition
    i.  Persentation files and local css and js files: c:\inserver6\worksheet\[alpha_num_folder_name], c:\inserver6\301YTCY_00LY2M6WQ000SD4\
    i.  Shared css and js files which are available for all Presentations: c:\inserver6\worksheet\shared</li>
<li></li>
</ol>

<h4>Using Form Designer</h4>

<ol>
<li><strong>Form Designer</strong> for basics
A.  Creates both xml and xsl base docs.
A.  Creates folder in ImageNow server root "e:/inserver6/worksheets" with unique ID (e.g., 301YTD7_00M2LXNM90016NM) for each presentation.
A.  Inside of the form folder are the documents for the form: images, css, xsl, js, etc.
A.  XML files are in the "e:/inserver6/worksheets/data_definition" folder.
A.  <strong>NOTE</strong>: The form <em>name</em> is created when the form is published. It is not automatically derived from any existing document.
A.  <strong>NOTE</strong>: a form <strong>is</strong> a DocType and the form name is also the DocType.
A.  The relationsihp between the DataDefinition xml and the form component files is made in the Form Server database -- it is not explictly made in any of the documents themselves (there is no XPATH, for example, in the XSL file to identify the XML file)--see next item below.</li>
<li>Once published <strong>Form Designer</strong> <strong><em>CANNOT</em></strong> be used to modify the forms or form components. <strong>MUST</strong> use the manual developer process.</li>
<li><strong>ImageNow</strong> -> <strong>Management Console</strong> -> <strong>Forms</strong> -> <strong>ManageFormComponents</strong> establishes database linkages between xml/xsl/css form components. One <strong>CAN</strong> here upload modified files, if desired (can also use SFTP to do the same).
A.  Data Definitions are the xml files. Can Add here. <strong>Add</strong> opens a <strong>FileOpen</strong> dialog to upload from local system.
A.  Shared Files are <em>available</em> to <strong>ALL</strong> presentations in the Forms system, and thus to multiple presentations simultaneously. <strong>EVERY</strong> file in Shared Files must be individually added to whatever Presentation necessary. This is a royal PITA.
    i.  Work item -- can paths in the Presentation xls be used to access Share Files? In the <strong>Using External Files</strong> section below, from the eForms Designer class, it appears that one must using the <strong>Manage Form Components</strong> process to do this.
A.  We really should have in the Shared Files folder default css and images for UW-Madison branding!
A.  Presentations include xsl, image, and css files. Can Create, Rename, Modify, and Remove here. <strong>But no options is presented for downloading to local computer for editing</strong>. Must use provided SFTP access to do this.
    i.  <strong>Create</strong>. Makes a new empty "container" for xsl, image, and css files which can all then be associated with a DataDefinition file. 
    i.  <strong>Modify</strong>. After Create, click on new Presentation object and select Modify to modify name, add description and upload Files.
    i.  Rename/Remove are obvious.
    i.  See steps below for how to set things up <strong><em>without</em></strong> using <strong>Form Designer</strong>.</li>
</ol>

<h4>Using External Files</h4>

<p>Steps from eForm Developer Course for creating Form objects and associating the required XML/XSL/CSS file with it.</p>

<p>These are the steps to get a form and its components installed within <strong>ImageNow</strong>.</p>

<ol>
<li>Login to <strong>ImageNow</strong></li>
<li>In the <strong>ImageNow</strong> toolbar, click <strong>Manage</strong></li>
<li>In the left pane of the <strong>ImageNow Management Console</strong> window, click <strong>Forms</strong>.</li>
<li>In the Forms tab click <strong>Manage Form Components...</strong></li>
<li>The DataDefinition files
A.  In the left pane of the <strong>Manage Form Components</strong> window, select <strong>Data Definition</strong>.
A.  Click the <strong>Add</strong> button and browse to the folder which contains the xml, xsl, css, and/or images files for the form.</li>
<li>The Shared components (e.g., css and images).
A.  In the <strong>Manage Form Components</strong> window, select <strong>Shared Files</strong> from the left pane.
A.  Click the <strong>Add</strong> button and browse to the location of the shared folder and select the appropriate files.</li>
<li>The <strong>Presentation</strong> (i.e., xsl) files
A.  In the <strong>Manage Form Components</strong> window select <strong>Presentations</strong> from the left pane.
A.  Click the <strong>Create</strong> button, and name the new presentation and press <strong>Return</strong>
A.  Select the newly created presentation and click on the <strong>Modify</strong> button to modify it.
A.  If you receive a message regarding changes that could affect the presentation, Save the changes.
A.  In the <strong>Presentation</strong> window, click on <strong>Files</strong> from the left pane. Click on <strong>Add</strong> and browse to your download folder. Select the xsl file(s) and click <strong>Open</strong> to bring them into the presentation. <strong>Note</strong>: This step needs to be done for <strong>each</strong> presentation file if there are more than one. Multiple files can be selected at the same time. <strong>At least one xsl file must be present (though there can be more than one xsl presentation file for a data-definition xml file).</strong>
A.  On this same dialog click the <strong>Select Shared Files</strong> button, and select the shared file(s) (eg., css) added in the <strong>Shared Components</strong> step above.
A.  Click <strong>OK</strong> to close the <strong>Presentation</strong> window.
A.  Click <strong>OK</strong> to close the <strong>Manage Form Components</strong> window.</li>
<li>Create the new Form and associate the DataDefintion, Shared, and Presentation files with it.
A.  In the <strong>ImageNow Management Console</strong> window, with <strong>Forms</strong> still selected, click the <strong>New</strong> button on the right side of the window.
A.  Type a name for the new form.
A.  From the right side of the <strong>ImageNow Management Console</strong> window click the <strong>Modify</strong> button.
A.  In the <strong>Form</strong> window, select <strong>Components</strong> from the left pane.
A.  From <strong>Data Definition</strong> drop-down menu select the form name as appropriate.
A.  In the <strong>Presentations</strong> section below, click the <strong>Select</strong> button on the right side.
A.  Select the appropriate presentation and click <strong>OK</strong>.
A.  Click <strong>OK</strong> to close the <strong>Form</strong> window.</li>
</ol>

<h4>Development Process</h4>

<p>The Form Designer can be used to create either a simple eForm. Or it can be used to create base DataDefinition/Presentation files. If a form needs any further modifications <strong>after it is published</strong>, the Form Designer CANNOT be used. The manual method must be used.</p>

<p><strong><em>WHAT ABOUT TEST -> PROD??</em></strong></p>

<p>How might this work exactly?? See <strong>Good Gawd</strong> below!</p>

<p>To use manually edited files.</p>

<ol>
<li>Either use Form Designer to create the base docs, or create them in editor of choice.
A.  Create some XML, XSL, and CSS templates!
A.  If Form Designer is used, files must be downloaded to local system using SFTP (WinSCP on MBP/Win7 has a saved connection).
A.  Use SublimeText to edit files -- but you <em>cannot</em> test them outside of the FormServer. Recall that the linkage between DataDefinition XML, XSL, CSS, and image files is done in the database and not internally within the files themselves, as would be true for such files on an Apache webserver. There are no XPATH statements or CSS links to link the files. Perhaps could use for local testing, but likely would break when uploaded to the Forms Server, or more likely would break how they work on the Forms Server.</li>
<li>Upload back to IN server
A.  Either use <strong>Management Console (local desktop) -> Form</strong> area for uploading <strong>OVER</strong> existing files.
A.  Or use SFTP to upload to  (polynomial [test] and parabola [prod]). If using SFTP can perhaps configure local environment to help with this part.</li>
<li>To view forms in ImageNow client
A.  For now, login to <strong>ImageNow</strong> client.
A.  In the <strong>ImageNow Explorer</strong> select <strong>Documents</strong>.
A.  Select Document "zzdemo" (bottom of the list) -- explore setting up an eForms Test DocType for eForm dev purpoases.
A.  Click on the <strong>Go</strong> search button to generate a list of documents of the zzdemo type.
A.  Double-click on the first item in the search results.
A.  The <strong>ImageNow Viewer</strong> will open. From the <strong>View</strong> menu select <strong>Forms</strong> -or- press the <strong>F12</strong> key to toggle form visibility.
A.  <strong>F7</strong> will toggle the right-side Properties view. Better disabled to maximize form visibility.
A.  When the Form View is enabled, a dropdown menu will be visible at the top of the form, from which <strong>all</strong> system forms can be selected. Select the desired form.</li>
<li><strong>If any form component (xml, xsl, css) is modified</strong> (yes, any component):
A.  Follow the process to upload the modified file to the Form Server.
A.  Close <strong>ImageNow Viewer</strong> and go through the "View Forms in ImageNow Client" to make the changes visible.
A.  Yes, every damn time.
A.  <em>*If you want to see changes via the Forms Server (not in the IN desktop client as in the steps above), you *</em>must bounce the Forms Server on curve (test) or conic (prod).</li>
<li>Debugging
A.  Cannot use server log files per DavidT. The Form Server is a java application delivered via Tomcat and its processes are contained and not exposed. So, what can one do?
A.  Create Debug code in javascript. Does javascript have a preparser directive mechanism by which I can add C-like "if DEBUG" statements?</li>
<li>Good Gawd!
A.  Right now, David uses two open RDP sessions, one to Test and one to Prod, and he manually copies files from Test -> Prod.
A.  Then, because the databases are not synced, and the internal database references for the XML data definition files will be different between Test and Prod (because Test and Prod are synced but once a month), he has to <strong>manually</strong> edit the master forms server .xml file (under /etc/) which contains the data necessary to map a form's URL  parameters to DocType fields <em>and</em> the primary database reference numbers, should those be different between the environments.
A.  I say again, <strong>GOOD GAWDAMIGHTY!!</strong></li>
</ol>

Evernote: None
Evernote: Perceptive eForm Notes/Processes
Evernote: []
Evernote: [id num here (I think)]
Evernote: <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note>
<!-- Sublime:[much alpha-num characters here]>
<h3>Perceptive eForm Process</h3>

<h4>Basic System Topology</h4>

<h5>Test</h5>

<p>Servers are:</p>

<ol>
<li>ImageNow
A.  Hostname: polynomial.doit.wisc.edu
A.  Paths
    i.  Data definitions, Presentations, Shared files: e:\inserver6\worksheets
    i.  imagenowforms.xml: e:\inserver6\etc</li>
<li>Forms Server
A.  Hostname: curve.doit.wisc.edu
A.  Use Windows Services to bounch Tomcat (?)</li>
</ol>

<h5>Prod</h5>

<p>Servers are:</p>

<ol>
<li>ImageNow
A.  Hostname: parabola.doit.wisc.edu
A.  Paths
    i.  Data definitions, Presentations, Shared files: e:\inserver6\worksheets
    i.  imagenowforms.xml: e:\inserver6\etc</li>
<li>Forms Server
A.  Hostname: conic.doit.wisc.edu
A.  Use Windows Services to bounch Tomcat (?)</li>
</ol>

<h5>What's Where</h5>

<p>Two types of <strong>form</strong> objects in ImageNow:</p>

<ol>
<li><strong>Worksheets</strong> are created with the Form Designer, associated with a DocTypes, and published. They are used from within the ImageNow client and are visible when a doctype with which they are associated is open. Use the <strong>Document Viewer</strong> option <strong>View Forms</strong> (F12) to show the <strong>Form Viewer</strong> pane on which is a dropdown menu of avaiable worksheets. See <strong>Forms</strong> next for a complicating issue. These worksheets allow post-import data manipulation via the worksheet's form fields (rather than, say, using the IndexKey/Custom Property view to manually edit field contents).</li>
<li><strong>eForms</strong> can also be created with the Form Designer and associated with a DocType, and published, and manipulated with the ImageNow client. But, they can also be presented to end-users via the Form Server. There need be no difference in functionality between an eForm and  a worksheet. But one major difference is that using a worksheet requires the IN client and an IN account. Using an eForm does not require an IN account and thus any UW entity can be the target audience for an eForm including registered students. The major caveat is that the Form Server uses a java applet to deliver the content to the end-user, so the browser/OS must have java technologies installed and correctly configured in the browser being used.</li>
<li>Because of the differences between these two types of forms, there is a file that contains specifications for which of the forms are in fact <strong>eForms</strong>, the .xml file located in c:\inserverg\etc\imagenowforms.xml. In this file will be a separate <DOCUMENT FORM> entry for each published <strong>eForm</strong>.  It will only contain <strong>eForms</strong> which are delivered by the Form Server and does not list <strong>Worksheets</strong>. At present there is <em>no</em> internal documentation that lists/shows which of the forms in e:\inserver6\worksheets\data_definition are <strong>eForms</strong> or <strong>Worksheets</strong> -- if a record is kept, it must be done manually.</li>
<li>Configuration of <strong>Worksheets</strong> and <strong>eForms</strong>
A.  All <strong>Worksheets</strong> and <strong>eForms</strong> will have their Data Definiton xml, Presentation xsl, and other files on the primary ImageNow server:
    i.  Data Definition files: c:\inserver6\worksheet\data_definition
    i.  Persentation files and local css and js files: c:\inserver6\worksheet\[alpha_num_folder_name], c:\inserver6\301YTCY_00LY2M6WQ000SD4\
    i.  Shared css and js files which are available for all Presentations: c:\inserver6\worksheet\shared</li>
<li></li>
</ol>

<h4>Using Form Designer</h4>

<ol>
<li><strong>Form Designer</strong> for basics
A.  Creates both xml and xsl base docs.
A.  Creates folder in ImageNow server root "e:/inserver6/worksheets" with unique ID (e.g., 301YTD7_00M2LXNM90016NM) for each presentation.
A.  Inside of the form folder are the documents for the form: images, css, xsl, js, etc.
A.  XML files are in the "e:/inserver6/worksheets/data_definition" folder.
A.  <strong>NOTE</strong>: The form <em>name</em> is created when the form is published. It is not automatically derived from any existing document.
A.  <strong>NOTE</strong>: a form <strong>is</strong> a DocType and the form name is also the DocType.
A.  The relationsihp between the DataDefinition xml and the form component files is made in the Form Server database -- it is not explictly made in any of the documents themselves (there is no XPATH, for example, in the XSL file to identify the XML file)--see next item below.</li>
<li>Once published <strong>Form Designer</strong> <strong><em>CANNOT</em></strong> be used to modify the forms or form components. <strong>MUST</strong> use the manual developer process.</li>
<li><strong>ImageNow</strong> -> <strong>Management Console</strong> -> <strong>Forms</strong> -> <strong>ManageFormComponents</strong> establishes database linkages between xml/xsl/css form components. One <strong>CAN</strong> here upload modified files, if desired (can also use SFTP to do the same).
A.  Data Definitions are the xml files. Can Add here. <strong>Add</strong> opens a <strong>FileOpen</strong> dialog to upload from local system.
A.  Shared Files are <em>available</em> to <strong>ALL</strong> presentations in the Forms system, and thus to multiple presentations simultaneously. <strong>EVERY</strong> file in Shared Files must be individually added to whatever Presentation necessary. This is a royal PITA.
    i.  Work item -- can paths in the Presentation xls be used to access Share Files? In the <strong>Using External Files</strong> section below, from the eForms Designer class, it appears that one must using the <strong>Manage Form Components</strong> process to do this.
A.  We really should have in the Shared Files folder default css and images for UW-Madison branding!
A.  Presentations include xsl, image, and css files. Can Create, Rename, Modify, and Remove here. <strong>But no options is presented for downloading to local computer for editing</strong>. Must use provided SFTP access to do this.
    i.  <strong>Create</strong>. Makes a new empty "container" for xsl, image, and css files which can all then be associated with a DataDefinition file. 
    i.  <strong>Modify</strong>. After Create, click on new Presentation object and select Modify to modify name, add description and upload Files.
    i.  Rename/Remove are obvious.
    i.  See steps below for how to set things up <strong><em>without</em></strong> using <strong>Form Designer</strong>.</li>
</ol>

<h4>Using External Files</h4>

<p>Steps from eForm Developer Course for creating Form objects and associating the required XML/XSL/CSS file with it.</p>

<p>These are the steps to get a form and its components installed within <strong>ImageNow</strong>.</p>

<ol>
<li>Login to <strong>ImageNow</strong></li>
<li>In the <strong>ImageNow</strong> toolbar, click <strong>Manage</strong></li>
<li>In the left pane of the <strong>ImageNow Management Console</strong> window, click <strong>Forms</strong>.</li>
<li>In the Forms tab click <strong>Manage Form Components...</strong></li>
<li>The DataDefinition files
A.  In the left pane of the <strong>Manage Form Components</strong> window, select <strong>Data Definition</strong>.
A.  Click the <strong>Add</strong> button and browse to the folder which contains the xml, xsl, css, and/or images files for the form.</li>
<li>The Shared components (e.g., css and images).
A.  In the <strong>Manage Form Components</strong> window, select <strong>Shared Files</strong> from the left pane.
A.  Click the <strong>Add</strong> button and browse to the location of the shared folder and select the appropriate files.</li>
<li>The <strong>Presentation</strong> (i.e., xsl) files
A.  In the <strong>Manage Form Components</strong> window select <strong>Presentations</strong> from the left pane.
A.  Click the <strong>Create</strong> button, and name the new presentation and press <strong>Return</strong>
A.  Select the newly created presentation and click on the <strong>Modify</strong> button to modify it.
A.  If you receive a message regarding changes that could affect the presentation, Save the changes.
A.  In the <strong>Presentation</strong> window, click on <strong>Files</strong> from the left pane. Click on <strong>Add</strong> and browse to your download folder. Select the xsl file(s) and click <strong>Open</strong> to bring them into the presentation. <strong>Note</strong>: This step needs to be done for <strong>each</strong> presentation file if there are more than one. Multiple files can be selected at the same time. <strong>At least one xsl file must be present (though there can be more than one xsl presentation file for a data-definition xml file).</strong>
A.  On this same dialog click the <strong>Select Shared Files</strong> button, and select the shared file(s) (eg., css) added in the <strong>Shared Components</strong> step above.
A.  Click <strong>OK</strong> to close the <strong>Presentation</strong> window.
A.  Click <strong>OK</strong> to close the <strong>Manage Form Components</strong> window.</li>
<li>Create the new Form and associate the DataDefintion, Shared, and Presentation files with it.
A.  In the <strong>ImageNow Management Console</strong> window, with <strong>Forms</strong> still selected, click the <strong>New</strong> button on the right side of the window.
A.  Type a name for the new form.
A.  From the right side of the <strong>ImageNow Management Console</strong> window click the <strong>Modify</strong> button.
A.  In the <strong>Form</strong> window, select <strong>Components</strong> from the left pane.
A.  From <strong>Data Definition</strong> drop-down menu select the form name as appropriate.
A.  In the <strong>Presentations</strong> section below, click the <strong>Select</strong> button on the right side.
A.  Select the appropriate presentation and click <strong>OK</strong>.
A.  Click <strong>OK</strong> to close the <strong>Form</strong> window.</li>
</ol>

<h4>Development Process</h4>

<p>The Form Designer can be used to create either a simple eForm. Or it can be used to create base DataDefinition/Presentation files. If a form needs any further modifications <strong>after it is published</strong>, the Form Designer CANNOT be used. The manual method must be used.</p>

<p><strong><em>WHAT ABOUT TEST -> PROD??</em></strong></p>

<p>How might this work exactly?? See <strong>Good Gawd</strong> below!</p>

<p>To use manually edited files.</p>

<ol>
<li>Either use Form Designer to create the base docs, or create them in editor of choice.
A.  Create some XML, XSL, and CSS templates!
A.  If Form Designer is used, files must be downloaded to local system using SFTP (WinSCP on MBP/Win7 has a saved connection).
A.  Use SublimeText to edit files -- but you <em>cannot</em> test them outside of the FormServer. Recall that the linkage between DataDefinition XML, XSL, CSS, and image files is done in the database and not internally within the files themselves, as would be true for such files on an Apache webserver. There are no XPATH statements or CSS links to link the files. Perhaps could use for local testing, but likely would break when uploaded to the Forms Server, or more likely would break how they work on the Forms Server.</li>
<li>Upload back to IN server
A.  Either use <strong>Management Console (local desktop) -> Form</strong> area for uploading <strong>OVER</strong> existing files.
A.  Or use SFTP to upload to  (polynomial [test] and parabola [prod]). If using SFTP can perhaps configure local environment to help with this part.</li>
<li>To view forms in ImageNow client
A.  For now, login to <strong>ImageNow</strong> client.
A.  In the <strong>ImageNow Explorer</strong> select <strong>Documents</strong>.
A.  Select Document "zzdemo" (bottom of the list) -- explore setting up an eForms Test DocType for eForm dev purpoases.
A.  Click on the <strong>Go</strong> search button to generate a list of documents of the zzdemo type.
A.  Double-click on the first item in the search results.
A.  The <strong>ImageNow Viewer</strong> will open. From the <strong>View</strong> menu select <strong>Forms</strong> -or- press the <strong>F12</strong> key to toggle form visibility.
A.  <strong>F7</strong> will toggle the right-side Properties view. Better disabled to maximize form visibility.
A.  When the Form View is enabled, a dropdown menu will be visible at the top of the form, from which <strong>all</strong> system forms can be selected. Select the desired form.</li>
<li><strong>If any form component (xml, xsl, css) is modified</strong> (yes, any component):
A.  Follow the process to upload the modified file to the Form Server.
A.  Close <strong>ImageNow Viewer</strong> and go through the "View Forms in ImageNow Client" to make the changes visible.
A.  Yes, every damn time.
A.  <em>*If you want to see changes via the Forms Server (not in the IN desktop client as in the steps above), you *</em>must bounce the Forms Server on curve (test) or conic (prod).</li>
<li>Debugging
A.  Cannot use server log files per DavidT. The Form Server is a java application delivered via Tomcat and its processes are contained and not exposed. So, what can one do?
A.  Create Debug code in javascript. Does javascript have a preparser directive mechanism by which I can add C-like "if DEBUG" statements?</li>
<li>Good Gawd!
A.  Right now, David uses two open RDP sessions, one to Test and one to Prod, and he manually copies files from Test -> Prod.
A.  Then, because the databases are not synced, and the internal database references for the XML data definition files will be different between Test and Prod (because Test and Prod are synced but once a month), he has to <strong>manually</strong> edit the master forms server .xml file (under /etc/) which contains the data necessary to map a form's URL  parameters to DocType fields <em>and</em> the primary database reference numbers, should those be different between the environments.
A.  I say again, <strong>GOOD GAWDAMIGHTY!!</strong></li>
</ol>
</en-note>
Evernote error: [Enml validation]
	Attribute name "FORM" associated with an element type "DOCUMENT" must be followed by the ' = ' character.
	Last command:  {}
	BEFORE SUBMITTING AN ISSUE (https://github.com/bordaigorl/sublime-evernote/issues):
	  1. Enable the `debug` setting in your Evernote.sublime-settings file and try again. If the problem persists take a note of the output in the console.
	     Make sure you delete personal information (e.g. Developer Token) from the output before posting it in an issue.
	  2. Check the wiki at https://github.com/bordaigorl/sublime-evernote/wiki
	  3. Search for similar issues at https://github.com/bordaigorl/sublime-evernote/issues?q=is%3Aissue
	(Evernote plugin v2.6.0, ST 3065, Python 3.3.3, windows x64, debug)
```

**Comment by bordaigorl** [comment]
Hi, the problem is that the contents of your note are interpreted as Markdown which is not the same as HTML even if it supports embedding some HTML within it.
In particular, in order to allow you to embed HTML, angle brackets `<` and `>` are not escaped.
In your case, `<DOCUMENT FORM>` (which presumably was meant to be inserted verbatim in the contents and not interpreted as a tag) is read as an XML tag by Evernote and that's why it complains about the unknown `FORM` attribute.
A simple solution is to replace that with something like `&lt;DOCUMENT FORM&gt;`.

**Comment by gstalnaker** [comment]
Doh! I should have seen that! Thanks.

“Happiness is the meaning and the purpose of life, the whole aim and end of human existence.”
¯ Aristotle

----- Reply message -----
